subprojects {
    apply plugin: 'java-library'

    version = project.mod_version
    group = project.maven_group

    repositories {
        mavenCentral()
        maven {
            url "https://maven.fabricmc.net/"
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 17
    }

    sourceSets {
        main {
            java.srcDirs = ['../../common/main/java', '../src/main/java', 'src/main/java']
            resources.srcDirs = ['../../common/main/resources', '../src/main/resources', 'src/main/resources']
        }
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(17)
        archivesBaseName = "IVR-FABRIC-${project.minecraft_version}"
    }

    plugins.withId('fabric-loom') {
        tasks.named('remapJar') {
            destinationDirectory = file('../mods')
        }
        tasks.register('copyJar', Delete) {
            delete layout.buildDirectory.dir('devlibs')
        }
        tasks.named('assemble') {
            finalizedBy 'copyJar'
        }
    }

    dependencies {
        implementation 'com.google.code.gson:gson:2.14.0'
    }
}
