subprojects {
    apply plugin: 'java-library'

    version = project.mod_version
    group = project.maven_group

    repositories {
        mavenCentral()
        maven {
            url "https://maven.fabricmc.net/"
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 17
    }

    dependencies {
        implementation 'com.google.code.gson:gson:2.14.0'
    }

    sourceSets {
        main {
            java {
                srcDirs = ['../../common/main/java', 'src/main/java']  // 指向共用源码
            }
            resources {
                srcDirs = ['../../common/main/resources', 'src/main/resources']
            }
        }
    }
}
