pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

// Fabric and Forge are independent builds with their own version subprojects.
includeBuild('fabric')
includeBuild('forge')
