package net.hulan.ivr;

import mtr.RegistryObject;
import mtr.block.BlockStationColor;
import mtr.block.BlockStationColorSlab;
import net.hulan.ivr.block.*;
import net.minecraft.block.*;

public interface IVRBlocks {

    RegistryObject<Block> CLASSICAL_SIGN_1_EVEN = new RegistryObject<>(() -> new BlockClassicalSign(1, false));
    RegistryObject<Block> CLASSICAL_SIGN_1_ODD = new RegistryObject<>(() -> new BlockClassicalSign(1, true));
    RegistryObject<Block> CLASSICAL_SIGN_2_EVEN = new RegistryObject<>(() -> new BlockClassicalSign(2, false));
    RegistryObject<Block> CLASSICAL_SIGN_2_ODD = new RegistryObject<>(() -> new BlockClassicalSign(2, true));
    RegistryObject<Block> CLASSICAL_SIGN_3_EVEN = new RegistryObject<>(() -> new BlockClassicalSign(3, false));
    RegistryObject<Block> CLASSICAL_SIGN_3_ODD = new RegistryObject<>(() -> new BlockClassicalSign(3, true));
    RegistryObject<Block> CLASSICAL_SIGN_4_EVEN = new RegistryObject<>(() -> new BlockClassicalSign(4, false));
    RegistryObject<Block> CLASSICAL_SIGN_4_ODD = new RegistryObject<>(() -> new BlockClassicalSign(4, true));
    RegistryObject<Block> CLASSICAL_SIGN_5_EVEN = new RegistryObject<>(() -> new BlockClassicalSign(5, false));
    RegistryObject<Block> CLASSICAL_SIGN_5_ODD = new RegistryObject<>(() -> new BlockClassicalSign(5, true));
    RegistryObject<Block> CLASSICAL_SIGN_6_EVEN = new RegistryObject<>(() -> new BlockClassicalSign(6, false));
    RegistryObject<Block> CLASSICAL_SIGN_6_ODD = new RegistryObject<>(() -> new BlockClassicalSign(6, true));
    RegistryObject<Block> CLASSICAL_SIGN_7_EVEN = new RegistryObject<>(() -> new BlockClassicalSign(7, false));
    RegistryObject<Block> CLASSICAL_SIGN_7_ODD = new RegistryObject<>(() -> new BlockClassicalSign(7, true));
    RegistryObject<Block> CLASSICAL_SIGN_POLE = new RegistryObject<>(BlockClassicalSignPole::new);
    RegistryObject<Block> CLASSICAL_SIGN_MIDDLE = new RegistryObject<>(() -> new BlockClassicalSign(0, false));
    RegistryObject<Block> MODERN_SIGN_1_EVEN = new RegistryObject<>(() -> new BlockModernSign(1, false));
    RegistryObject<Block> MODERN_SIGN_1_ODD = new RegistryObject<>(() -> new BlockModernSign(1, true));
    RegistryObject<Block> MODERN_SIGN_2_EVEN = new RegistryObject<>(() -> new BlockModernSign(2, false));
    RegistryObject<Block> MODERN_SIGN_2_ODD = new RegistryObject<>(() -> new BlockModernSign(2, true));
    RegistryObject<Block> MODERN_SIGN_3_EVEN = new RegistryObject<>(() -> new BlockModernSign(3, false));
    RegistryObject<Block> MODERN_SIGN_3_ODD = new RegistryObject<>(() -> new BlockModernSign(3, true));
    RegistryObject<Block> MODERN_SIGN_4_EVEN = new RegistryObject<>(() -> new BlockModernSign(4, false));
    RegistryObject<Block> MODERN_SIGN_4_ODD = new RegistryObject<>(() -> new BlockModernSign(4, true));
    RegistryObject<Block> MODERN_SIGN_5_EVEN = new RegistryObject<>(() -> new BlockModernSign(5, false));
    RegistryObject<Block> MODERN_SIGN_5_ODD = new RegistryObject<>(() -> new BlockModernSign(5, true));
    RegistryObject<Block> MODERN_SIGN_6_EVEN = new RegistryObject<>(() -> new BlockModernSign(6, false));
    RegistryObject<Block> MODERN_SIGN_6_ODD = new RegistryObject<>(() -> new BlockModernSign(6, true));
    RegistryObject<Block> MODERN_SIGN_7_EVEN = new RegistryObject<>(() -> new BlockModernSign(7, false));
    RegistryObject<Block> MODERN_SIGN_7_ODD = new RegistryObject<>(() -> new BlockModernSign(7, true));
    RegistryObject<Block> MODERN_SIGN_POLE = new RegistryObject<>(BlockModernSignPole::new);
    RegistryObject<Block> MODERN_SIGN_MIDDLE = new RegistryObject<>(() -> new BlockModernSign(0, false));
    RegistryObject<Block> KCR_STATION_WALL = new RegistryObject<>(() -> new Block(AbstractBlock.Settings.copy(Blocks.PURPUR_PILLAR)));
    RegistryObject<Block> KCR_STATION_WALL_SLAB = new RegistryObject<>(() -> new SlabBlock(AbstractBlock.Settings.copy(Blocks.PURPUR_PILLAR)));
    RegistryObject<Block> KCR_STATION_COLOR_STATION_WALL = new RegistryObject<>(() -> new BlockStationColor(AbstractBlock.Settings.copy(KCR_STATION_WALL.get())));
    RegistryObject<Block> KCR_STATION_COLOR_STATION_WALL_SLAB = new RegistryObject<>(() -> new BlockStationColorSlab(AbstractBlock.Settings.copy(KCR_STATION_WALL_SLAB.get())));
    RegistryObject<Block> KCR_PLATFORM_NORMAL = new RegistryObject<>(BlockKCRPlatform::new);
    RegistryObject<Block> KCR_PLATFORM_YELLOW_LINE = new RegistryObject<>(BlockKCRPlatform::new);
    RegistryObject<Block> KCR_PLATFORM_INDENTED = new RegistryObject<>(BlockKCRPlatformIndented::new);
    RegistryObject<Block> KCR_CLOCK = new RegistryObject<>(BlockKCRClock::new);
    RegistryObject<Block> KCR_CLOCK_POLE = new RegistryObject<>(BlockKCRClockPole::new);
    RegistryObject<Block> KCR_CEILING_AUTO = new RegistryObject<>(() -> new BlockKCRCeilingAuto(AbstractBlock.Settings.of(Material.METAL, MapColor.OFF_WHITE).requiresTool().strength(2.0F).luminance((state) -> 15)));
    RegistryObject<Block> KCR_CEILING_LIGHT = new RegistryObject<>(() -> new BlockKCRCeiling(AbstractBlock.Settings.of(Material.METAL, MapColor.OFF_WHITE).requiresTool().strength(2.0F).luminance((state) -> 15)));
    RegistryObject<Block> KCR_CEILING_NO_LIGHT = new RegistryObject<>(() -> new BlockKCRCeiling(AbstractBlock.Settings.of(Material.METAL, MapColor.OFF_WHITE).requiresTool().strength(2.0F)));
    RegistryObject<Block> IVR_LOGO = new RegistryObject<>(() -> new Block(AbstractBlock.Settings.of(Material.METAL, MapColor.GRAY).requiresTool().strength(2.0F).luminance((state) -> 10)));
    RegistryObject<Block> KCR_APG_DOOR = new RegistryObject<>(BlockKCRAPGDoor::new);
    RegistryObject<Block> KCR_APG_GLASS = new RegistryObject<>(BlockKCRAPGGlass::new);
    RegistryObject<Block> KCR_APG_GLASS_END = new RegistryObject<>(BlockKCRAPGGlassEnd::new);
    RegistryObject<Block> KCR_PSD_DOOR_1 = new RegistryObject<>(() -> new BlockKCRPSDDoor(0));
    RegistryObject<Block> KCR_PSD_GLASS_1 = new RegistryObject<>(() -> new BlockKCRPSDGlass(0));
    RegistryObject<Block> KCR_PSD_GLASS_END_1 = new RegistryObject<>(() -> new BlockKCRPSDGlassEnd(0));
    RegistryObject<Block> KCR_PSD_DOOR_2 = new RegistryObject<>(() -> new BlockKCRPSDDoor(1));
    RegistryObject<Block> KCR_PSD_GLASS_2 = new RegistryObject<>(() -> new BlockKCRPSDGlass(1));
    RegistryObject<Block> KCR_PSD_GLASS_END_2 = new RegistryObject<>(() -> new BlockKCRPSDGlassEnd(1));
    RegistryObject<Block> KCR_PSD_TOP = new RegistryObject<>(BlockKCRPSDTop::new);
    RegistryObject<Block> KCR_STATION_NAME_ENTRANCE = new RegistryObject<>(BlockKCRStationNameEntrance::new);
    RegistryObject<Block> KCR_STATION_NAME_TALL_BLOCK = new RegistryObject<>(BlockKCRStationNameTallBlock::new);
    RegistryObject<Block> KCR_STATION_NAME_TALL_BLOCK_DOUBLE_SIDED = new RegistryObject<>(BlockKCRStationNameTallBlockDoubleSided::new);
    RegistryObject<Block> KCR_STATION_NAME_TALL_WALL = new RegistryObject<>(BlockKCRStationNameTallWall::new);
    RegistryObject<Block> KCR_STATION_NAME_WALL_WHITE = new RegistryObject<>(BlockKCRStationNameWallWhite::new);
    RegistryObject<Block> KCR_STATION_NAME_WALL_GRAY = new RegistryObject<>(BlockKCRStationNameWallGray::new);
    RegistryObject<Block> KCR_STATION_NAME_WALL_BLACK = new RegistryObject<>(BlockKCRStationNameWallBlack::new);
    RegistryObject<Block> MODERN_ROUTE = new RegistryObject<>(BlockModernRouteSign::new);
}
