allprojects {
    version = project.findProperty('mod_version') ?: '1.2-beta'
    group = project.findProperty('maven_group') ?: 'net.hulan'

    repositories {
        mavenCentral()
        maven { url = 'https://maven.minecraftforge.net/' }
    }
}

subprojects {
    apply plugin: 'java-library'

    dependencies {
        implementation 'com.google.code.gson:gson:2.14.0'
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 17
    }
}
