plugins {
    id 'fabric-loom' version '1.6-SNAPSHOT'
}

repositories {
    maven { url = "some.repository.org" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation(files("lib/MTR-fabric-1.18.2-3.2.2-hotfix-1.jar"))

    // Common:
    annotationProcessor 'org.ow2.asm:asm-debug-all:5.2'
    annotationProcessor 'com.google.guava:guava:32.1.2-jre'
    annotationProcessor 'com.google.code.gson:gson:2.8.9'
}

sourceSets {
    main {
        java {
            srcDirs = ['../common/main/java', '/src/main/java']  // 指向共用源码
        }
        resources {
            srcDirs = ['../common/main/resources', '/src/main/resources']
        }
    }
}

def targetJavaVersion = 17
tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release = targetJavaVersion
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    archivesBaseName = "IVR-" + "${project.minecraft_version}"
}

remapJar {
    destinationDirectory = file("../mods")
}

tasks.register('copyJar', Delete) {
    delete "$buildDir/devlibs"
}

assemble.finalizedBy('copyJar')