package net.hulan.ivr;

import mtr.RegistryObject;
import mtr.mappings.RegistryUtilities;
import net.hulan.ivr.block.*;
import net.minecraft.world.level.block.entity.BlockEntityType;

public interface IVRBlockEntityTypes {

    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign>> CLASSICAL_SIGN_1_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockClassicalSign.TileEntityClassicalSign(1, false, pos, state), IVRBlocks.CLASSICAL_SIGN_1_EVEN.get()));
    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign1Odd>> CLASSICAL_SIGN_1_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType(BlockClassicalSign.TileEntityClassicalSign1Odd::new, IVRBlocks.CLASSICAL_SIGN_1_ODD.get()));
    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign>> CLASSICAL_SIGN_2_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockClassicalSign.TileEntityClassicalSign(2, false, pos, state), IVRBlocks.CLASSICAL_SIGN_2_EVEN.get()));
    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign>> CLASSICAL_SIGN_2_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockClassicalSign.TileEntityClassicalSign(2, true, pos, state), IVRBlocks.CLASSICAL_SIGN_2_ODD.get()));
    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign>> CLASSICAL_SIGN_3_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockClassicalSign.TileEntityClassicalSign(3, false, pos, state), IVRBlocks.CLASSICAL_SIGN_3_EVEN.get()));
    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign>> CLASSICAL_SIGN_3_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockClassicalSign.TileEntityClassicalSign(3, true, pos, state), IVRBlocks.CLASSICAL_SIGN_3_ODD.get()));
    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign>> CLASSICAL_SIGN_4_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockClassicalSign.TileEntityClassicalSign(4, false, pos, state), IVRBlocks.CLASSICAL_SIGN_4_EVEN.get()));
    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign>> CLASSICAL_SIGN_4_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockClassicalSign.TileEntityClassicalSign(4, true, pos, state), IVRBlocks.CLASSICAL_SIGN_4_ODD.get()));
    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign>> CLASSICAL_SIGN_5_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockClassicalSign.TileEntityClassicalSign(5, false, pos, state), IVRBlocks.CLASSICAL_SIGN_5_EVEN.get()));
    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign>> CLASSICAL_SIGN_5_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockClassicalSign.TileEntityClassicalSign(5, true, pos, state), IVRBlocks.CLASSICAL_SIGN_5_ODD.get()));
    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign>> CLASSICAL_SIGN_6_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockClassicalSign.TileEntityClassicalSign(6, false, pos, state), IVRBlocks.CLASSICAL_SIGN_6_EVEN.get()));
    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign>> CLASSICAL_SIGN_6_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockClassicalSign.TileEntityClassicalSign(6, true, pos, state), IVRBlocks.CLASSICAL_SIGN_6_ODD.get()));
    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign>> CLASSICAL_SIGN_7_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockClassicalSign.TileEntityClassicalSign(7, false, pos, state), IVRBlocks.CLASSICAL_SIGN_7_EVEN.get()));
    RegistryObject<BlockEntityType<BlockClassicalSign.TileEntityClassicalSign>> CLASSICAL_SIGN_7_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockClassicalSign.TileEntityClassicalSign(7, true, pos, state), IVRBlocks.CLASSICAL_SIGN_7_ODD.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_1_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(1, false, pos, state), IVRBlocks.MODERN_SIGN_1_EVEN.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_1_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(1, true, pos, state), IVRBlocks.MODERN_SIGN_1_ODD.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_2_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(2, false, pos, state), IVRBlocks.MODERN_SIGN_2_EVEN.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_2_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(2, true, pos, state), IVRBlocks.MODERN_SIGN_2_ODD.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_3_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(3, false, pos, state), IVRBlocks.MODERN_SIGN_3_EVEN.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_3_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(3, true, pos, state), IVRBlocks.MODERN_SIGN_3_ODD.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_4_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(4, false, pos, state), IVRBlocks.MODERN_SIGN_4_EVEN.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_4_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(4, true, pos, state), IVRBlocks.MODERN_SIGN_4_ODD.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_5_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(5, false, pos, state), IVRBlocks.MODERN_SIGN_5_EVEN.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_5_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(5, true, pos, state), IVRBlocks.MODERN_SIGN_5_ODD.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_6_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(6, false, pos, state), IVRBlocks.MODERN_SIGN_6_EVEN.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_6_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(6, true, pos, state), IVRBlocks.MODERN_SIGN_6_ODD.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_7_EVEN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(7, false, pos, state), IVRBlocks.MODERN_SIGN_7_EVEN.get()));
    RegistryObject<BlockEntityType<BlockModernSign.TileEntityModernSign>> MODERN_SIGN_7_ODD_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockModernSign.TileEntityModernSign(7, true, pos, state), IVRBlocks.MODERN_SIGN_7_ODD.get()));
    RegistryObject<BlockEntityType<BlockKCRClock.TileEntityKCRClock>> KCR_CLOCK_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType(BlockKCRClock.TileEntityKCRClock::new, IVRBlocks.KCR_CLOCK.get()));
    RegistryObject<BlockEntityType<BlockKCRPSDDoor.TileEntityKCRPSDDoor>> KCR_PSD_DOOR_1_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockKCRPSDDoor.TileEntityKCRPSDDoor(0, pos, state), IVRBlocks.KCR_PSD_DOOR_1.get()));
    RegistryObject<BlockEntityType<BlockKCRPSDDoor.TileEntityKCRPSDDoor>> KCR_PSD_DOOR_2_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType((pos, state) -> new BlockKCRPSDDoor.TileEntityKCRPSDDoor(1, pos, state), IVRBlocks.KCR_PSD_DOOR_2.get()));
    RegistryObject<BlockEntityType<BlockKCRPSDTop.TileEntityKCRPSDTop>> KCR_PSD_TOP_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType(BlockKCRPSDTop.TileEntityKCRPSDTop::new, IVRBlocks.KCR_PSD_TOP.get()));
    RegistryObject<BlockEntityType<BlockKCRAPGGlass.TileEntityKCRAPGGlass>> KCR_APG_GLASS_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType(BlockKCRAPGGlass.TileEntityKCRAPGGlass::new, IVRBlocks.KCR_APG_GLASS.get()));
    RegistryObject<BlockEntityType<BlockKCRAPGDoor.TileEntityKCRAPGDoor>> KCR_APG_DOOR_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType(BlockKCRAPGDoor.TileEntityKCRAPGDoor::new, IVRBlocks.KCR_APG_DOOR.get()));
    RegistryObject<BlockEntityType<BlockKCRStationNameEntrance.TileEntityKCRStationNameEntrance>> KCR_STATION_NAME_ENTRANCE_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType(BlockKCRStationNameEntrance.TileEntityKCRStationNameEntrance::new, IVRBlocks.KCR_STATION_NAME_ENTRANCE.get()));
    RegistryObject<BlockEntityType<BlockKCRStationNameWallWhite.TileEntityKCRStationNameWallWhite>> KCR_STATION_NAME_WALL_WHITE_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType(BlockKCRStationNameWallWhite.TileEntityKCRStationNameWallWhite::new, IVRBlocks.KCR_STATION_NAME_WALL_WHITE.get()));
    RegistryObject<BlockEntityType<BlockKCRStationNameWallGray.TileEntityKCRStationNameWallGray>> KCR_STATION_NAME_WALL_GRAY_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType(BlockKCRStationNameWallGray.TileEntityKCRStationNameWallGray::new, IVRBlocks.KCR_STATION_NAME_WALL_GRAY.get()));
    RegistryObject<BlockEntityType<BlockKCRStationNameWallBlack.TileEntityKCRStationNameWallBlack>> KCR_STATION_NAME_WALL_BLACK_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType(BlockKCRStationNameWallBlack.TileEntityKCRStationNameWallBlack::new, IVRBlocks.KCR_STATION_NAME_WALL_BLACK.get()));
    RegistryObject<BlockEntityType<BlockKCRStationNameTallBlock.TileEntityKCRStationNameTallBlock>> KCR_STATION_NAME_TALL_BLOCK_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType(BlockKCRStationNameTallBlock.TileEntityKCRStationNameTallBlock::new, IVRBlocks.KCR_STATION_NAME_TALL_BLOCK.get()));
    RegistryObject<BlockEntityType<BlockKCRStationNameTallBlockDoubleSided.TileEntityKCRStationNameTallBlockDoubleSided>> KCR_STATION_NAME_TALL_BLOCK_DOUBLE_SIDED_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType(BlockKCRStationNameTallBlockDoubleSided.TileEntityKCRStationNameTallBlockDoubleSided::new, IVRBlocks.KCR_STATION_NAME_TALL_BLOCK_DOUBLE_SIDED.get()));
    RegistryObject<BlockEntityType<BlockKCRStationNameTallWall.TileEntityKCRStationNameTallWall>> KCR_STATION_NAME_TALL_WALL_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType(BlockKCRStationNameTallWall.TileEntityKCRStationNameTallWall::new, IVRBlocks.KCR_STATION_NAME_TALL_WALL.get()));
    RegistryObject<BlockEntityType<BlockModernRouteSign.TileEntityModernRouteSign>> MODERN_ROUTE_SIGN_TILE_ENTITY = new RegistryObject<>(() -> RegistryUtilities.getBlockEntityType(BlockModernRouteSign.TileEntityModernRouteSign::new, IVRBlocks.MODERN_ROUTE.get()));
}
