plugins {
    id 'net.minecraftforge.gradle' version '[5.1,6.0)'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
}

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { url = 'https://maven.architectury.dev/' }
    maven { url = 'https://maven.fabricmc.net/' }
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
    implementation fg.deobf('me.shedaniel:architectury-forge:1.32.66')
    implementation(files("lib/MTR-forge-1.16.5-3.2.2-hotfix-1.jar"))

    // Common:
    annotationProcessor 'org.ow2.asm:asm-debug-all:5.2'
    annotationProcessor 'com.google.guava:guava:32.1.2-jre'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

mixin {
    add sourceSets.main, 'IVR.refmap.json'
    config 'IVR.mixins.json'
    config 'ksd.mixins.json'
}

minecraft {
    mappings channel: 'official', version: project.minecraft_version
}

