plugins {
    id 'net.minecraftforge.gradle' version '[5.1,6.0)'
}

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { url = 'https://maven.architectury.dev/' }
    maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
    implementation fg.deobf('dev.architectury:architectury-forge:8.2.89')
    implementation(files("lib/MTR-forge-1.19.4-3.2.2-hotfix-1.jar"))


    // Common:
    annotationProcessor 'org.ow2.asm:asm-debug-all:5.2'
    annotationProcessor 'com.google.guava:guava:32.1.2-jre'
    annotationProcessor 'com.google.code.gson:gson:2.8.9'
}

minecraft {
    mappings channel: 'official', version: project.minecraft_version
}

