plugins {
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'dev.architectury.loom' version '1.13.469'
}

loom { silentMojangMappingsLicense() }

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
    modImplementation 'dev.architectury:architectury-forge:6.6.92'
    modImplementation(files("lib/MTR-forge-1.19.2-3.2.2-hotfix-1.jar"))
    implementation 'com.google.code.gson:gson:2.14.0'
    compileOnly(annotationProcessor('io.github.llamalad7:mixinextras-common:0.5.5'))
    implementation(include('io.github.llamalad7:mixinextras-forge:0.5.5'))
    annotationProcessor 'org.ow2.asm:asm-debug-all:5.2'
    annotationProcessor 'com.google.guava:guava:32.1.2-jre'
    annotationProcessor 'com.google.code.gson:gson:2.8.9'
}

architectury { minecraft = project.minecraft_version }

